name: Build Android APK
on: push

jobs:
  build:
    runs-on: ubuntu-22.04  # On force Ubuntu 22.04 au lieu de latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
